const products = [{
        name: 'kill this love',
        img: '/data/kill.jpg',
        nameG: 'BLACKPINK',
        typeG: 'Female group',
        company: 'YG entertainment',
        imgDes: '/data/Dkill.jpg',
        imgSell: '/data/Pkill.jpg',
        miniTitle: 'BLACKPINK Mini Album Vol. 2 - KILL THIS LOVE',
        intro: '* CD + Booklet (52 P) + Photo Zine (16 P) + Accordion Lyrics Book (10 P) + 4 Random Photocards + 1 Random Polaroid + Sticker Set + Folded Poster (On Pack).',
        date: 2019,
        price: 16.35,
        Rdate: '2019.04.23',
        code: '8809634380036',
        trackList: ['Kill This Love', 'Don’t Know What To Do', 'Kick It', '아니길 (Hope Not)', '뚜두뚜두 (DDU-DU DDU-DU) (Remix)'],
        imgGa: '/data/kill1.jpg',
        imgGb: '/data/kill2.jpg',
        imgGc: '/data/kill3.jpg'
    },
    {
        name: 'timeless',
        img: '/data/suju.jpg',
        nameG: 'Super Junior',
        typeG: 'Male group',
        company: 'SM Entertainment',
        imgDes: '/data/Dsuju.jpg',
        imgSell: '/data/Psuju.jpg',
        miniTitle: 'Super Junior Vol. 9 - TIMELESS',
        intro: '* CD + Booklet (104 P) + Random Tag + Folded Poster (On Pack) + Random Photocard * Provided totally random.',
        date: 2019,
        price: 17.08,
        Rdate: '2020.01.29',
        code: '8809440339563',
        trackList: ['The crown', 'SUPER clap', 'I think I', 'Somebody New', 'Heads Up', 'Stay with me', 'No drama', 'Show'],
        imgGa: '/data/suju1.jpg',
        imgGb: '/data/suju2.jpg',
        imgGc: '/data/suju3.jpg'
    },
    {
        name: 'Layers',
        img: '/data/layer.jpg',
        nameG: 'Ong Seong Wu',
        typeG: 'solo',
        company: 'Fantagio',
        imgDes: '/data/Dlayer.jpg',
        imgSell: '/data/Player.jpg',
        miniTitle: 'Ong Seong Wu Mini Album Vol. 1 - LAYERS',
        intro: '* CD + Booklet (124 P) + Name Card * Postcard Set : Preorder benefit. First press only.',
        date: 2020,
        price: 11.48,
        Rdate: '2020.03.26',
        code: '8804775140181',
        trackList: ['GRAVITY', '너를 위한 카페 (Cafe)', '또, 다시 나를 마주한 채 (After Dark)', 'BYE BYE', 'GUESS WHO', 'WE BELONG'],
        imgGa: '/data/layer1.jpg',
        imgGb: '/data/layer2.jpg',
        imgGc: '/data/layer3.jpg'
    },
    {
        name: 'Reality in black',
        img: '/data/mamamoo.jpg',
        nameG: 'MAMAMOO',
        typeG: 'Female group',
        company: 'Victor Entertainment',
        imgDes: '/data/Dmamamoo.jpg',
        imgSell: '/data/Pmamamoo.jpg',
        miniTitle: 'MAMAMOO Album Vol. 2 - Reality In BLACK',
        intro: '* CD + Booklet (80 P) + Lenticular Card + Lyrics Card (12 P) + Random Photocard (2 P)',
        date: 2019,
        price: 15.55,
        Rdate: '2019.11.15',
        code: '8804775136047',
        trackList: ['우린 결국 다시 만날 운명이었니 (Destiny)', '열 밤 (Ten Nights)', 'HIP - title', '4x4ever', 'Hello Mama', 'REALITY', '춤을 춰 (High Tension)', 'I’m Your Fan'],
        imgGa: '/data/mama1.jpg',
        imgGb: '/data/mama2.jpg',
        imgGc: '/data/mama3.jpg'
    },
    {
        name: 'DYE',
        img: '/data/got7.jpg',
        nameG: 'GOT7',
        typeG: 'Male group',
        company: 'JYP Entertainment',
        imgDes: '/data/Ddye.jpg',
        imgSell: '/data/Pdye.jpg',
        miniTitle: 'GOT7 Mini Album - DYE',
        intro: '* CD + Booklet (80 P) + Random Bookmark + Random Photocard (2 P) Random GOT7 Tourlog Photo Essay Vol. 2 (60 P) + Random Lyrics Postcard : Preorder benefit. First press only.',
        date: 2020,
        price: 13.69,
        Rdate: '2020.04.21',
        code: '8809440339778',
        trackList: ['AURA', 'CRAZY', 'NOT BY THE MOON *title', 'LOVE YOU BETTER', 'TRUST MY LOVE', 'POISON'],
        imgGa: '/data/dye1.jpg',
        imgGb: '/data/dye2.jpg',
        imgGc: '/data/dye3.jpg'
    },
    {
        name: 'Color on me',
        img: '/data/color.jpg',
        nameG: 'Kang Daniel',
        typeG: 'Solo',
        company: 'Konnect Entertainment',
        imgDes: '/data/Dcolor.jpg',
        imgSell: '/data/Pcolor.jpg',
        miniTitle: 'Kang Daniel Mini Album - Color On Me',
        intro: '* CD + Booklet (76 P) + 1 Random Clear Film + 1 Random Photocard + Postcard (3 P) + Sticker + Bookmark',
        date: 2019,
        price: 14.13,
        Rdate: '2019.07.29',
        code: '8803581201239',
        trackList: ['Intro (Through the night)', 'Color', '뭐해 (What are you up to)', 'Horizon', 'I HOPE'],
        imgGa: '/data/color1.jpg',
        imgGb: '/data/color2.jpg',
        imgGc: '/data/color3.jpg'
    },
    {
        name: 'The perfect red',
        img: '/data/red.jpg',
        nameG: 'Red Velvet',
        typeG: 'Female group',
        company: 'SM Entertainment',
        imgDes: '/data/Dred.jpg',
        imgSell: '/data/Pred.jpg',
        miniTitle: 'Red Velvet Vol. 2 - THE PERFECT RED VELVET',
        intro: '* CD + Booklet (56 P) + Lyrics Sheet (24 P) + 1 Random Photocard',
        date: 2018,
        price: 14.99,
        Rdate: '2018.01.30',
        code: '8809269508850',
        trackList: ['Bad Boy', '피카부 (Peek-A- Boo)', '봐 (Look)', 'Kingdom Come', 'Time To Love', '두 번째 데이트 (My Second Date)', 'Attaboy', 'Perfect 10', ],
        imgGa: '/data/red1.jpg',
        imgGb: '/data/red2.jpg',
        imgGc: '/data/red3.jpg'
    },
    {
        name: 'Map of soul: 7',
        img: '/data/bts.jpg',
        nameG: 'BTS',
        typeG: 'Male group',
        company: 'BigHit Entertainment',
        imgDes: '/data/Dbts.jpg',
        imgSell: '/data/Pbts.jpg',
        miniTitle: 'BTS - MAP OF THE SOUL : 7',
        intro: '* CD + Booklet (36 P) + Lyric Book (52 P) + Mini Book (20 P) + Random Photocard + Postcard + Sticker + Coloring Paper.',
        date: 2020,
        price: 20.42,
        Rdate: '2020.02.21',
        code: '8809440339532',
        trackList: ['Into : Persona', '작은 것들을 위한 시(Boy With Luv) (Feat. Halsey)', 'Make It Right', 'Jamais Vu', 'Dionysus', 'Interlude : Shadow', 'Black Swan'],
        imgGa: '/data/bts1.jpg',
        imgGb: '/data/bts2.jpg',
        imgGc: '/data/bts3.jpg'
    },

    {
        name: 'WHY',
        img: '/data/why.jpg',
        nameG: 'Jeong Min',
        typeG: 'Solo',
        company: 'Startship Entertainment',
        imgDes: '/data/Dwhy.jpg',
        imgSell: '/data/Pwhy.jpg',
        miniTitle: 'JEONG MIN Single Album Vol. 2 - Why?',
        intro: '* CD + Booklet (20 P) + 1 Random Photocard, Secret Card : Totally random. Included in part of first press albums only.',
        date: 2019,
        price: 13.47,
        Rdate: '2019.11.07',
        code: '8809696000255',
        trackList: ['왜 그땐 몰랐을까', '비가 오는데', '왜 그땐 몰랐을까 (inst.)', '비가 오는데 (inst.)'],
        imgGa: '/data/why1.jpg',
        imgGb: '/data/why2.jpg',
        imgGc: '/data/why3.jpg'
    },
    {
        name: 'I trust',
        img: '/data/trust.jpg',
        nameG: '(G)I-DLE',
        typeG: 'Female group',
        company: 'Cube Entertainment',
        imgDes: '/data/Dtrust.jpg',
        imgSell: '/data/Ptrust.jpg',
        miniTitle: '(G)I-DLE Mini Album Vol. 3 - I TRUST',
        intro: '* CD + Booklet (100 P) + Random Brochure + Random Mini Poster (On Pack) + Random Photocard + Random Translucent Photocard + Random Lenticular Photocard',
        date: 2020,
        price: 11.89,
        Rdate: '2020.04.07',
        code: '8804775141232',
        trackList: ['Oh my god - title', '사랑해', 'Maybe', 'LION', 'Oh my god (English Ver.)'],
        imgGa: '/data/trust1.jpg',
        imgGb: '/data/trust2.jpg',
        imgGc: '/data/trust3.jpg'
    },
    {

        name: 'One & only',
        img: '/data/astro.jpg',
        nameG: 'ASTRO',
        typeG: 'Male group',
        company: 'Fantagio',
        imgDes: '/data/Donly.jpg',
        imgSell: '/data/Ponly.jpg',
        miniTitle: 'ASTRO Special Single Album - ONE & ONLY',
        intro: '* CD + Booklet (72 P) + Random Message Card + Random Photocard (Group 1 P, Selfie 1 P), Signed Polaroid : Totally random. Included in part of first press albums only.',
        date: 2020,
        price: 10.55,
        Rdate: '2020.03.13',
        code: '8809696001368',
        trackList: ['ONE&ONLY *Title', 'ONE&ONLY (Inst.)'],
        imgGa: '/data/astro1.jpg',
        imgGb: '/data/astro2.jpg',
        imgGc: '/data/astro3.jpg'
    },
    {

        name: 'Flourishing',
        img: '/data/chungHa.jpg',
        nameG: 'Chung Ha',
        typeG: 'Solo',
        company: 'MNH Entretainment',
        imgDes: '/data/Dchunga.jpg',
        imgSell: '/data/Pchunga.jpg',
        miniTitle: 'Chung Ha Mini Album Vol. 4 - Flourishing',
        intro: '* CD + Booklet (76 P) + Lyrics (8 P) + 1 Random Postcard + 1 Random Photocard',
        date: 2019,
        price: 13.48,
        Rdate: '2019.06.25',
        code: '8809658312938',
        trackList: ['Chica', '우리가 즐거워', 'Call It Love', 'Flourishing', 'Snapping * Title'],
        imgGa: '/data/chunga1.jpg',
        imgGb: '/data/chunga2.jpg',
        imgGc: '/data/chunga3.jpg'
    },
    {

        name: 'ITZ ICY',
        img: '/data/itzy.jpg',
        nameG: 'ITZY',
        typeG: 'Female group',
        company: 'JYP Entertainment',
        imgDes: '/data/Ditzy.jpg',
        imgSell: '/data/Pitzy.jpg',
        miniTitle: 'ITZY - IT’z ICY',
        intro: '* CD + Photobook (80 P) * Provided totally random.',
        date: 2019,
        price: 11.76,
        Rdate: '2019.07.30',
        code: '8809440338979',
        trackList: ['ICY [TITLE*]', 'CHERRY', 'IT’z SUMMER', '달라달라 (DallasK Remix)', 'WANT IT? (I-mad Royal Remix)'],
        imgGa: '/data/itzy1.jpg',
        imgGb: '/data/itzy2.jpg',
        imgGc: '/data/itzy3.jpg'
    },
    {

        name: 'Dazzle Dazzle',
        img: '/data/weki.jpg',
        nameG: 'Weki Meki',
        typeG: 'Female group',
        company: 'Fantagio',
        imgDes: '/data/Dweki.jpg',
        imgSell: '/data/Pweki.jpg',
        miniTitle: 'Weki Meki SINGLE DAZZLE DAZZLE OFFICIAL MD',
        intro: '* Color Pet Sleeve + Postcard Book (30 P) + Random Selfie Photocard',
        date: 2020,
        price: 12.59,
        Rdate: '2020.02.10',
        code: '8804775076015',
        trackList: ['SINGLE DAZZLE DAZZLE'],
        imgGa: '/data/weki1.jpg',
        imgGb: '/data/weki2.jpg',
        imgGc: '/data/weki3.jpg'
    },
    {

        name: 'Obsession',
        img: '/data/exo.jpg',
        nameG: 'EXO',
        typeG: 'Male group',
        company: 'SM Entertainment',
        imgDes: '/data/Dexo.jpg',
        imgSell: '/data/Pexo.jpg',
        miniTitle: 'EXO Album Vol. 6 - OBSESSION',
        intro: '* CD + Lyric Book (32 P) + Booklet (20 P * 6 EA) + Folded Poster (On Pack) + Photo Slide + Random Photocard. Provided totally random.',
        date: 2019,
        price: 16.53,
        Rdate: '2019.11.28',
        code: '8809440339433',
        trackList: ['Obsession', '지킬 (Jekyll)', '춤 (Groove)', 'Ya Ya Ya', 'Baby You Are', 'Non Stop', '오늘도 (Day After Day)', '나비효과 (Butterfly Effect)'],
        imgGa: '/data/exo1.jpg',
        imgGb: '/data/exo2.jpg',
        imgGc: '/data/exo3.jpg'
    },
    {

        name: 'Love poem',
        img: '/data/lovepoem.jpg',
        nameG: 'IU',
        typeG: 'solo',
        company: 'Kakao M',
        imgDes: '/data/Dlove.jpg',
        imgSell: '/data/Plove.jpg',
        miniTitle: 'IU Mini Album Vol. 5 - Love Poem',
        intro: '* CD + Booklet (112 P) + Photocard + Bookmark',
        date: 2019,
        price: 12.99,
        Rdate: '2019.11.20',
        code: '8804775136351',
        trackList: ['Unlucky', 'The visitor', 'Blueming', 'Above the time', 'Lullaby', 'Love poem'],
        imgGa: '/data/love1.jpg',
        imgGb: '/data/love2.jpg',
        imgGc: '/data/love3.jpg'
    },
    {

        name: 'fantasia',
        img: '/data/monsta.jpg',
        nameG: 'MONSTA X',
        typeG: 'Male group',
        company: 'Startship Entertainment',
        imgDes: '/data/Dmonsta.jpg',
        imgSell: '/data/Pmonsta.jpg',
        miniTitle: 'MONSTA X Mini Album - FANTASIA X',
        intro: '* CD + Booklet (108 P) + Random Photocard + Sticker * Unit Photocard + Color Polaroid + Triangle Stand : Preorder benefit.',
        date: 2020,
        price: 28.99,
        Rdate: '2020.05.12',
        code: '8804775142444',
        trackList: ['Fantasia', 'Flow', 'Zone', 'Chaotic', 'Beautiful night', 'It ain’t over', 'Stand up'],
        imgGa: '/data/fanta1.jpg',
        imgGb: '/data/fanta2.jpg',
        imgGc: '/data/fanta3.jpg'
    },
    {

        name: 'plant',
        img: '/data/plant.jpg',
        nameG: 'Se Jeong',
        typeG: 'Solo',
        company: 'Jellyfish Entertainment',
        imgDes: '/data/Dplant.jpg',
        imgSell: '/data/Pplant.jpg',
        miniTitle: 'Se Jeong (Gugudan) Mini Album Vol. 1 - Plant',
        intro: '* CD + Booklet (64 P) + Random Bookmark + Random Postcard + Se Jeongs Letter + Random Photocard',
        date: 2020,
        price: 11.45,
        Rdate: '2020.03.18',
        code: '8809704412599',
        trackList: ['화분', '오늘은 괜찮아', 'SKYLINE', '오리발', '꿈속에서 널'],
        imgGa: '/data/plant1.jpg',
        imgGb: '/data/plant2.jpg',
        imgGc: '/data/plant3.jpg'
    },
    {

        name: 'Poison',
        img: '/data/poison.jpg',
        nameG: 'VAV',
        typeG: 'Male group',
        company: 'Ateam',
        imgSell: '/data/Ppoison.jpg',
        imgDes: '/data/Dpoison.jpg',
        miniTitle: 'VAV Mini Album Vol. 5 - POISON',
        intro: '* CD + Booklet (88 P) + Folded Poster (On Pack) + 1 Random Photocard',
        date: 2019,
        price: 11.12,
        Rdate: '2019.10.22',
        code: '8809314513693',
        trackList: ['Poison', '119', 'Runway', 'Sweet Heart', 'Poison (inst.)'],
        imgGa: '/data/vav1.jpg',
        imgGb: '/data/vav2.jpg',
        imgGc: '/data/vav3.jpg'
    },
    {

        name: 'going seventeen',
        img: '/data/seventeen.jpg',
        nameG: 'Seventeen',
        typeG: 'Male group',
        company: 'Pledis Entertainment',
        imgDes: '/data/Dseven.jpg',
        imgSell: '/data/Pseventeen.jpg',
        miniTitle: 'Seventeen Mini Album Vol.3 - Going Seventeen',
        intro: '* CD + Booklet (100 P) + Lyrics Paper (8 P) + Boarding Declaration Sheet + 1 Random Member Photocard + 1 Random Unit Photocard + 1 Random Paddle Bookmark',
        date: 2016,
        price: 14.15,
        Rdate: ' 2016.12.06',
        code: '8804775076022',
        trackList: ['BEAUTIFUL', '붐붐', 'HIGHLIGHT', '기대', '빠른 걸음', '몰래 듣지 마요', '글쎄', '웃음꽃'],
        imgGa: '/data/seven1.jpg',
        imgGb: '/data/seven2.jpg',
        imgGc: '/data/seven3.jpg'
    },

    {

        name: 'gateway',
        img: '/data/gateway.jpg',
        nameG: 'Astro',
        typeG: 'Male group',
        company: 'Fantagio',
        imgDes: '/data/Dgateway.jpg',
        imgSell: '/data/Pgateway.jpg',
        miniTitle: 'ASTRO Mini Album Vol. 7 - GATEWAY',
        intro: '* CD + Booklet (72 P) + Folding Postcard + Random Selfie Photocard (2 P) + Random Folding Poster (On Pack)',
        date: 2020,
        price: 18.25,
        Rdate: ' 2020.05.07',
        code: '8804775142055',
        trackList: ['Knock (널찾아가) *Title', '내 이름을 부를 때', 'Somebody like', 'We still', '12시간', '빛이 돼 줄게'],
        imgGa: '/data/gate1.jpg',
        imgGb: '/data/gate2.jpg',
        imgGc: '/data/gate3.jpg'
    },
];
module.exports = products;