const products = [{
        name: 'kill this love',
        img: '/data/kill.jpg',
        nameG: 'BLACKPINK',
        typeG: 'Female group',
        company: 'YG entertainment',
        date: 2019,
        price: 16.35,
    },
    {
        name: 'timeless',
        img: '/data/suju.jpg',
        nameG: 'Super Junior',
        typeG: 'Male group',
        company: 'SM Entertainment',
        date: 2019,
        price: 17.08,
    },
    {
        name: 'Layers',
        img: '/data/layer.jpg',
        nameG: 'Ong Seong Wu',
        typeG: 'solo',
        company: 'Fantagio',
        date: 2020,
        price: 11.48,
    },
    {
        name: 'Reality in black',
        img: '/data/mamamoo.jpg',
        nameG: 'MAMAMOO',
        typeG: 'Female group',
        company: 'Victor Entertainment',
        date: 2019,
        price: 15.55,
    },
    {
        name: 'DYE',
        img: '/data/got7.jpg',
        nameG: 'GOT7',
        typeG: 'Male group',
        company: 'JYP Entertainment',
        date: 2020,
        price: 13.69,
    },
    {
        name: 'Color on me',
        img: '/data/color.jpg',
        nameG: 'Kang Daniel',
        typeG: 'Solo',
        company: 'Konnect Entertainment',
        date: 2019,
        price: 14.13,
    },
    {
        name: 'The perfect red',
        img: '/data/red.jpg',
        nameG: 'Red Velvet',
        typeG: 'Female group',
        company: 'SM Entertainment',
        date: 2018,
        price: 14.99,
    },
    {
        name: 'Map og soul: 7',
        img: '/data/bts.jpg',
        nameG: 'BTS',
        typeG: 'Male group',
        company: 'BigHit',
        date: 2020,
        price: 20.42,
    },

    {
        name: 'WHY?',
        img: '/data/why.jpg',
        nameG: 'Jeong Min',
        typeG: 'Solo',
        company: 'Startship Entertainment',
        date: 2019,
        price: 13.47,
    },
    {
        name: 'I trust',
        img: '/data/trust.jpg',
        nameG: '(G)I-DLE',
        typeG: 'Female group',
        company: 'Cube Entertainment',
        date: 2020,
        price: 11.89,
    },
    {

        name: 'One & only',
        img: '/data/astro.jpg',
        nameG: 'ASTRO',
        typeG: 'Male group',
        company: 'Fantagio',
        date: 2020,
        price: 10.55,
    },
    {

        name: 'Flourishing',
        img: '/data/chungHa.jpg',
        nameG: 'Chung Ha',
        typeG: 'Solo',
        company: 'MNH Entretainment',
        date: 2019,
        price: 13.48,
    },
    {

        name: 'ITZ ICY',
        img: '/data/itzy.jpg',
        nameG: 'ITZY',
        typeG: 'Female group',
        company: 'JYP Entertainment',
        date: 2019,
        price: 11.76,
    },
    {

        name: 'Dazzle Dazzle',
        img: '/data/weki.jpg',
        nameG: 'Weki Meki',
        typeG: 'Female group',
        company: 'Fantagio',
        date: 2020,
        price: 12.59,
    },
    {

        name: 'Obsession',
        img: '/data/exo.jpg',
        nameG: 'EXO',
        typeG: 'Male group',
        company: 'SM Entertainment',
        date: 2019,
        price: 16.53,
    },
    {

        name: 'Love poem',
        img: '/data/lovepoem.jpg',
        nameG: 'IU',
        typeG: 'solo',
        company: 'Kakao M',
        date: 2019,
        price: 12.99,
    },
    {

        name: 'All about love',
        img: '/data/monsta.jpg',
        nameG: 'MONSTA X',
        typeG: 'Male group',
        company: 'Startship Entertainment',
        date: 2020,
        price: 28.99,
    },
    {

        name: 'plant',
        img: '/data/plant.jpg',
        nameG: 'Se Jeong',
        typeG: 'Solo',
        company: 'Jellyfish Entertainment',
        date: 2020,
        price: 11.45,
    },
    {

        name: 'Poison',
        img: '/data/poison.jpg',
        nameG: 'VAV',
        typeG: 'Male group',
        company: 'Ateam',
        date: 2019,
        price: 11.12,
    },
    {

        name: 'going seventeen',
        img: '/data/seventeen.jpg',
        nameG: 'Seventeen',
        typeG: 'Male group',
        company: 'Pledis Entertainment',
        date: 2016,
        price: 14.15,
    },

    {

        name: 'gateway',
        img: '/data/gateway.jpg',
        nameG: 'Astro',
        typeG: 'Male group',
        company: 'Fantagio Entertainment',
        date: 2020,
        price: 18.25,
    },
];
module.exports = products;